name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.0.1'
      - name: Install app dependencies
        run: flutter pub get
      - name: Run linter
        run: flutter analyze --suppress-analytics
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install coverage tools
        run: sudo apt-get install lcov
      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.0.1'
      - name: Install app dependencies
        run: flutter pub get
      - name: Run widget and unit tests
        run: flutter test test --coverage --coverage-path coverage/lcov.base.info
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 29
            script: flutter test integration_test --coverage --merge-coverage
      - name: Upload coverage to Codecov 
        uses: codecov/codecov-action@v1 
        with: 
          token: ${{ secrets.CODECOV_TOKEN }} 
          file: coverage/lcov.info

